### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by coloriz** [coloriz/macOS-setup-playbook#1]
- [ ] config.yml에 추가적으로 설치할 패키지 명시 or post_provision_tasks로 처리할까
- [ ] ssh config 동기화 - iCloud Drive에 symlink로 처리
- [ ] ssh key 동기화는 어떻게 할까
